### ISSUE TITLE
NE on K8s: ensure NuvlaEdge reboot management action works

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/deployment#101]
- [x] investigate
- [x] propose a solution
- [x] implement

**Comment by giovannibianco** [comment]
First impression... there is no function for `reboot` within the kubernetes connector.
First pass... implement `reboot` function that just does pass to get past the docker-ish error messages.

**Comment by giovannibianco** [comment]
I think the UI can only send a command to reboot using `nuvla.job.actions.nuvlabox_reboot` which then triggers the `NBRebootJob` which, in turn, defines the connector as a NuvlaBox ... the reboot function then calls the reboot sequence from inside a docker container which is bound to `/proc/sysrq-trigger`

**Comment by giovannibianco** [comment]
Does it make sense to modify on the UI so that it does send a e.g. "KubernetesRebootJob" (instead of the NBRebootJob) which can then be run as a Kubernetes Job type with appropriate volume mount to the `/proc/sysrq-trigger`

**Comment by giovannibianco** [comment]
```
apiVersion: batch/v1
kind: Job
metadata:
  name: reboot
spec:
  template:
    spec:
      containers:
      - name: reboot
        image: busybox
        command: ['sh', '-c', 'echo b > /sysrq'] 
        volumeMounts:
        - name: reboot-vol
          mountPath: /sysrq
      volumes:
      - name: reboot-vol
        hostPath:
          path: /proc/sysrq-trigger
      restartPolicy: Never
  backoffLimit: 4
```
