### ISSUE TITLE
Add environment variables to allow for alternative docker registry and repo

### ISSUE THREAD

**Issue by schaubl** [nuvlaedge/deployment#92]
This allow to point to another docker registry.

The idea is to add this optional prefix on the docker-compose.yml files of NuvlaEdge components.

Also every docker image run by NuvlaEdge components (data-gateway, on-stop, ...) should have an env var to change the default image name.
These images could also be added into the docker-compose.yml file but with `scale: 0` so that they are pre-pulled but containers are not started.

Example:
```yaml

services:

  agent:
    image: ${DOCKER_REGISTRY:-}${NUVLAEDGE_REPO:-nuvlaedge}/system-manager:2.11.0
    
  job-engine-lite:
    image: ${DOCKER_REGISTRY:-}${NUVLA_REPO:-nuvla}/job-lite:3.2.7

```
